In [2]:
import pandas as pd
import numpy as np
import re
import string

import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\chami\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chami\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\chami\AppData\Roaming\nltk_data...

True

In [4]:
fake = pd.read_csv("../data/Fake.csv")
true = pd.read_csv("../data/True.csv")

In [5]:
fake["label"] = 0
true["label"] = 1

In [6]:
data = pd.concat([fake, true])

data = data.sample(frac=1).reset_index(drop=True)

data.head()

,title,text,subject,date,label
0,Was A Washington Post Reporter Caught Snapping...,Doris Truong is a reporter for the hard left-l...,politics,"Jan 12, 2017",0
1,"Exclusive: Presidential hopefuls Sanders, Clin...",NEW YORK (Reuters) - Vermont Senator Bernie Sa...,politicsNews,"February 5, 2016",1
2,New York judge weighs Cruz ballot challenge on...,"ALBANY, New York (Reuters) - A New York judge ...",politicsNews,"March 3, 2016",1
3,POLICE STATE END-RUN: DHS Wants Control of U.S...,21st Century Wire says Here s a classic case o...,Middle-east,"September 1, 2016",0
4,"California governor endorses Clinton, calls Tr...",WASHINGTON (Reuters) - California Governor Jer...,politicsNews,"May 31, 2016",1

In [7]:
data = data[["text", "label"]]

data.head()

                                                text  label
0  Doris Truong is a reporter for the hard left-l...      0
1  NEW YORK (Reuters) - Vermont Senator Bernie Sa...      1
2  ALBANY, New York (Reuters) - A New York judge ...      1
3  21st Century Wire says Here s a classic case o...      0
4  WASHINGTON (Reuters) - California Governor Jer...      1

In [8]:
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def clean_text(text):

    text = text.lower()

    text = re.sub(r"<.*?>", "", text)

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"\d+", "", text)

    text = text.translate(str.maketrans("", "", string.punctuation))

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word not in stop_words]

    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

In [9]:
data["clean_text"] = data["text"].apply(clean_text)

data.head()

LookupError:
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - 'C:\\Users\\chami/nltk_data'
    - 'C:\\Program Files\\Python313\\nltk_data'
    - 'C:\\Program Files\\Python313\\share\\nltk_data'
    - 'C:\\Program Files\\Python313\\lib\\nltk_data'
    - 'C:\\Users\\chami\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [10]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\chami\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [11]:
data["clean_text"] = data["text"].apply(clean_text)

data.head()

,text,label,clean_text
0,Doris Truong is a reporter for the hard left-l...,0,doris truong reporter hard leftleaning washing...
1,NEW YORK (Reuters) - Vermont Senator Bernie Sa...,1,new york reuters vermont senator bernie sander...
2,"ALBANY, New York (Reuters) - A New York judge ...",1,albany new york reuters new york judge thursda...
3,21st Century Wire says Here s a classic case o...,0,st century wire say classic case problem react...
4,WASHINGTON (Reuters) - California Governor Jer...,1,washington reuters california governor jerry b...

In [12]:
tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(data["clean_text"]).toarray()

y = data["label"]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [14]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(35918, 5000)
(8980, 5000)
(35918,)
(8980,)